### ISSUE TITLE
Using this kernel in the standard Talos image for x86 possible?

### ISSUE THREAD

**Issue by nogweii** [nberlee/kernel#2]
I was hoping to get your help to use your kernel in a custom built Talos image meant for a few Intel NUCs I run (alongside 4 RK1 in a Turing Pi 2).

As I understand it, I'll need to build my own installer image. I can do that by following the official documentation at https://www.talos.dev/v1.7/advanced/building-images/ but it is missing docs on how to select a customized kernel.

Also, I'd prefer not to upload the resulting OCI files to the public cloud as I'm trying to make this something that can be bootstrapped from just a single laptop. Which means I'd need a local registry running on my laptop, which Sidero Labs has helpfully documented already in https://www.talos.dev/v1.7/advanced/developing-talos/.

----

All of this is in order to get the UBSAN error fixed (mentioned in https://github.com/siderolabs/talos/issues/8780) :smile:

**Comment by nogweii** [comment]
Ah, you responded to me in the Discord thread, linking to [the steps performed by `@CamSub`](https://discord.com/channels/754950670175436841/1206962480803479603/1239479147990880346).

Seems like the key would be to override the make variable `PKG_KERNEL`.

**Comment by samip5** [comment]
> Ah, you responded to me in the Discord thread

What Discord server is this?

**Comment by nogweii** [comment]
Well I ended up getting distracted and not following up. Got the kernel to build locally, but couldn't solve the bootstrapped distribution problem with self-signed certificates. However, the upstream issue in talos has been resolved by them apply the same patch themselves. Just need to wait for the next release to be cut that includes the updated kernel. (Version 6.6.43 by the looks of it.)

**Comment by samip5** [comment]
I submitted the original PR for the patch to be included from this repo to talos's default kernel.
