### ISSUE TITLE
Building initramfs

### ISSUE THREAD

**Issue by samip5** [nberlee/kernel#4]
Hey!

It just occurred to me that the build doesn't appear to generate an initramfs or am I just missing something?

```
rebuilding initramfs with system extensions...
    copying /usr/install/arm64/initramfs.xz to /tmp/imager3648059616/initramfs.xz
failed to copy initramfs: error copying /usr/install/arm64/initramfs.xz -> /tmp/imager3648059616/initramfs.xz: open /usr/install/arm64/initramfs.xz: no such file or directory
Error: failed to copy initramfs: error copying /usr/install/arm64/initramfs.xz -> /tmp/imager3648059616/initramfs.xz: open /usr/install/arm64/initramfs.xz: no such file or directory
 ```

**Comment by nberlee** [comment]
an initramfs cannot be generated from a kernel package. As talos is part of the initramfs.

So this builds, then extensions repo and sbc-overlay repo builds and then the talos repo builds an imager which uses the extensinos and sbc-overlay, builds a initramfs file which is used by the installer image and image-metal

**Comment by nberlee** [comment]
Also this is not a full clone of siderolabs/pkgs. only the kernel as the version is the same to upstream, I only overwrite the kernel in the extension/sbc-overlay and talos
